name: Auto operation After deploy

on:  
  workflow_dispatch

jobs:
  tagging_merge_job:
    runs-on: ubuntu-latest
    steps:
      - name: Merge ${{ github.ref }} to main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ github.ref }}
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main -> dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
   
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
