name: Sync branch

on:  
  workflow_dispatch:
  workflow_run:
    workflows: ["S3 배포"]
    branches: [main]
    types: [completed]

jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync ${{ github.ref }} to main
        uses: devmasx/merge-branch@master
        with:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          type: now
          from_branch: ${{ github.ref }}
          target_branch: main  
          
      - name: Sync dev with main
        uses: devmasx/merge-branch@master
        with:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          type: now
          from_branch: main
          target_branch: dev
