name: 브랜치 싱크

on:  
  workflow_dispatch

jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Merge ${{ github.ref }} to main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ github.ref }}
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main -> dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
