name: Sync branch

on:  
  workflow_dispatch:

jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync ${{ github.ref }} to main
        uses: devmasx/merge-branch@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          type: now
          from_branch: ${{ github.ref }}
          target_branch: main  
          
      - name: Sync dev with main
        uses: devmasx/merge-branch@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          type: now
          from_branch: main
          target_branch: dev

      - uses: actions/checkout@master
        with:
          ref: main
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: release

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
