name: Sync branch

on:  
  workflow_dispatch

jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync ${{ github.ref }} to main
        uses: devmasx/merge-branch@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          type: now
          from_branch: ${{ github.ref }}
          target_branch: main  
          
      - name: Sync dev with master
        uses: devmasx/merge-branch@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          type: now
          from_branch: main
          target_branch: dev

      - uses: actions/checkout@master
      - name: Tag and prepare release
        id: tag_and_prepare_release
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release notes
        if: steps.tag_and_prepare_release.outputs.tag
        uses: Roang-zero1/github-create-release-action@master
        with:
          created_tag: ${{ steps.tag_and_prepare_release.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
