name: 브랜치 싱크

on:  
  workflow_dispatch

jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync ${{ github.ref }} to main
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: ${{ github.ref }}
          TO_BRANCH: "main"
          
      - name: Sync dev with master
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "dev"
